name: Build CustomWeapons JAR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle/wrapper/**') }}

      - name: Unzip source if present
        run: |
          if [ -f CustomWeapons-Source.zip ]; then
            unzip -o CustomWeapons-Source.zip
            ls -la
          else
            echo "No zip found in repo root; assuming source files are already present."
          fi

      - name: Build with Gradle (shadowJar)
        uses: gradle/gradle-build-action@v2
        with:
          arguments: '-p CustomWeapons shadowJar'

      - name: Upload built JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: customweapons-jar
          path: CustomWeapons/build/libs/*.jar
